/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.pidev.tests.dao;

import com.esprit.pidev.persistance.dao.CategorieDAO;
import com.esprit.pidev.persistance.dao.interfaces.ICategorieDAO;
import com.esprit.pidev.persistance.model.Categorie;
/**
 *
 * @author USER
 */
public class Ajoutercategorie extends javax.swing.JFrame {

    /**
     * Creates new form Ajoutercategorie
     */
    public Ajoutercategorie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelajout2 = new javax.swing.JPanel();
        typecat2 = new javax.swing.JTextField();
        label7 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        idcat2 = new javax.swing.JTextField();
        nomcat2 = new javax.swing.JTextField();
        label9 = new javax.swing.JLabel();
        boutton5 = new javax.swing.JButton();
        boutton6 = new javax.swing.JButton();
        btretour2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelajout2.setBackground(new java.awt.Color(153, 204, 255));
        panelajout2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255)), "Ajout_Catégorie", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18), new java.awt.Color(255, 102, 0))); // NOI18N

        typecat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typecat2ActionPerformed(evt);
            }
        });

        label7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label7.setText("ID:");

        label8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label8.setText("TYPE:");

        idcat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idcat2ActionPerformed(evt);
            }
        });

        nomcat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomcat2ActionPerformed(evt);
            }
        });

        label9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label9.setText("NOM:");

        boutton5.setText("Ajouter");
        boutton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutton5ActionPerformed(evt);
            }
        });

        boutton6.setText("Afficher");
        boutton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutton6ActionPerformed(evt);
            }
        });

        btretour2.setText("Retour");
        btretour2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btretour2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelajout2Layout = new javax.swing.GroupLayout(panelajout2);
        panelajout2.setLayout(panelajout2Layout);
        panelajout2Layout.setHorizontalGroup(
            panelajout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelajout2Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addGroup(panelajout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelajout2Layout.createSequentialGroup()
                        .addGroup(panelajout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label9)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label8))
                        .addGap(54, 54, 54)
                        .addGroup(panelajout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idcat2, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(nomcat2)
                            .addComponent(typecat2)))
                    .addGroup(panelajout2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(boutton5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(boutton6)))
                .addGap(55, 55, 55)
                .addComponent(btretour2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelajout2Layout.setVerticalGroup(
            panelajout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelajout2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelajout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idcat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label7))
                .addGap(43, 43, 43)
                .addGroup(panelajout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomcat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label9))
                .addGap(46, 46, 46)
                .addGroup(panelajout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typecat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label8))
                .addGap(74, 74, 74)
                .addGroup(panelajout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutton5)
                    .addComponent(btretour2)
                    .addComponent(boutton6))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(panelajout2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelajout2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typecat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typecat2ActionPerformed

    }//GEN-LAST:event_typecat2ActionPerformed

    private void idcat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idcat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idcat2ActionPerformed

    private void nomcat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomcat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomcat2ActionPerformed

    private void boutton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutton5ActionPerformed
        // TODO add your handling code here:
        Categorie cat=new Categorie();
        int x;
        x=Integer.parseInt(idcat2.getText());
        cat.setId(x);
        cat.setNom(nomcat2.getText());
        cat.setType(typecat2.getText());

        ICategorieDAO catdao=CategorieDAO.getInstance();
        catdao.save( cat);
        
    }//GEN-LAST:event_boutton5ActionPerformed

    private void boutton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutton6ActionPerformed

    private void btretour2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btretour2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Choix page = new Choix();
        page.setVisible(true);
    }//GEN-LAST:event_btretour2ActionPerformed

     
    
     
  
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajoutercategorie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajoutercategorie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajoutercategorie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajoutercategorie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajoutercategorie().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutton1;
    private javax.swing.JButton boutton2;
    private javax.swing.JButton boutton3;
    private javax.swing.JButton boutton4;
    private javax.swing.JButton boutton5;
    private javax.swing.JButton boutton6;
    private javax.swing.JButton btretour;
    private javax.swing.JButton btretour1;
    private javax.swing.JButton btretour2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField idcat;
    private javax.swing.JTextField idcat1;
    private javax.swing.JTextField idcat2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JTextField nomcat;
    private javax.swing.JTextField nomcat1;
    private javax.swing.JTextField nomcat2;
    private javax.swing.JPanel panelajout;
    private javax.swing.JPanel panelajout1;
    private javax.swing.JPanel panelajout2;
    private javax.swing.JTextField typecat;
    private javax.swing.JTextField typecat1;
    private javax.swing.JTextField typecat2;
    // End of variables declaration//GEN-END:variables
}
