/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.pidev.tests.dao;

/**
 *
 * @author USER
 */
public class Choix extends javax.swing.JFrame {

    /**
     * Creates new form Choix
     */
    public Choix() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelchoix = new javax.swing.JPanel();
        btmodifier = new javax.swing.JToggleButton();
        btsupprimer = new javax.swing.JToggleButton();
        btafficher = new javax.swing.JToggleButton();
        btajouter = new javax.swing.JToggleButton();
        label1 = new javax.swing.JLabel();
        retour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelchoix.setBackground(new java.awt.Color(153, 204, 255));
        panelchoix.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255)), "Gestion_categories", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 14), new java.awt.Color(255, 102, 0))); // NOI18N

        btmodifier.setBackground(new java.awt.Color(102, 204, 255));
        btmodifier.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btmodifier.setForeground(new java.awt.Color(255, 102, 0));
        btmodifier.setText("Modifier catégorie\n");
        btmodifier.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmodifierActionPerformed(evt);
            }
        });

        btsupprimer.setBackground(new java.awt.Color(102, 204, 255));
        btsupprimer.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btsupprimer.setForeground(new java.awt.Color(255, 102, 0));
        btsupprimer.setText("Supprimer catégorie");
        btsupprimer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsupprimerActionPerformed(evt);
            }
        });

        btafficher.setBackground(new java.awt.Color(102, 204, 255));
        btafficher.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btafficher.setForeground(new java.awt.Color(255, 102, 0));
        btafficher.setText("Afficher catégories");
        btafficher.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btafficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btafficherActionPerformed(evt);
            }
        });

        btajouter.setBackground(new java.awt.Color(102, 204, 255));
        btajouter.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btajouter.setForeground(new java.awt.Color(255, 102, 0));
        btajouter.setText("Ajouter catégorie\n");
        btajouter.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btajouterActionPerformed(evt);
            }
        });

        label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/pidev/tests/dao/user.png"))); // NOI18N

        retour.setText("Retour");
        retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelchoixLayout = new javax.swing.GroupLayout(panelchoix);
        panelchoix.setLayout(panelchoixLayout);
        panelchoixLayout.setHorizontalGroup(
            panelchoixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelchoixLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(retour, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(panelchoixLayout.createSequentialGroup()
                .addGroup(panelchoixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btafficher, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelchoixLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelchoixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelchoixLayout.createSequentialGroup()
                        .addComponent(btajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelchoixLayout.createSequentialGroup()
                        .addComponent(btsupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelchoixLayout.setVerticalGroup(
            panelchoixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelchoixLayout.createSequentialGroup()
                .addGroup(panelchoixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelchoixLayout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE))
                    .addGroup(panelchoixLayout.createSequentialGroup()
                        .addGap(0, 94, Short.MAX_VALUE)
                        .addComponent(btajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btsupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addComponent(btafficher, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(retour)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelchoix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(panelchoix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btajouterActionPerformed
        // TODO add yourthis.setVisible(false);

        Ajoutercategorie ajoutercategorie=new Ajoutercategorie();
        ajoutercategorie.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btajouterActionPerformed

    private void retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourActionPerformed
        // TODO add your handling code here:
        GestionCategories page = new GestionCategories();
        page.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_retourActionPerformed

    private void btmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmodifierActionPerformed
        // TODO add your handling code here:
        ModifierCategorie modifierCategorie=new ModifierCategorie();
        modifierCategorie.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btmodifierActionPerformed

    private void btsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsupprimerActionPerformed
        // TODO add your handling code here:
        Supprimercategorie supprimercategorie=new Supprimercategorie();
        supprimercategorie.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btsupprimerActionPerformed

    private void btafficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btafficherActionPerformed
        // TODO add your handling code here:
        Affichercategories affichercategories=new Affichercategories();
        affichercategories.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btafficherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choix().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btafficher;
    private javax.swing.JToggleButton btajouter;
    private javax.swing.JToggleButton btmodifier;
    private javax.swing.JToggleButton btsupprimer;
    private javax.swing.JLabel label1;
    private javax.swing.JPanel panelchoix;
    private javax.swing.JButton retour;
    // End of variables declaration//GEN-END:variables
}
