
package com.esprit.pidev.tests.dao;



public class GestionCategories extends javax.swing.JFrame {

    /**
     * Creates new form GestionCategories
     */
   
    public GestionCategories() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel1 = new javax.swing.JPanel();
        gestionoffre = new javax.swing.JToggleButton();
        gestionuser = new javax.swing.JToggleButton();
        stat = new javax.swing.JToggleButton();
        gestioncat = new javax.swing.JToggleButton();
        label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));

        panel1.setBackground(new java.awt.Color(153, 204, 255));
        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 255)), "Acceuil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 14), new java.awt.Color(255, 102, 0))); // NOI18N

        gestionoffre.setBackground(new java.awt.Color(102, 204, 255));
        gestionoffre.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        gestionoffre.setForeground(new java.awt.Color(255, 102, 0));
        gestionoffre.setText("Gestion des offres d'emploi");
        gestionoffre.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        gestionuser.setBackground(new java.awt.Color(102, 204, 255));
        gestionuser.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        gestionuser.setForeground(new java.awt.Color(255, 102, 0));
        gestionuser.setText("Gestion des comptes user");
        gestionuser.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        stat.setBackground(new java.awt.Color(102, 204, 255));
        stat.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        stat.setForeground(new java.awt.Color(255, 102, 0));
        stat.setText("Vérifier les statistiques");
        stat.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        gestioncat.setBackground(new java.awt.Color(102, 204, 255));
        gestioncat.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        gestioncat.setForeground(new java.awt.Color(255, 102, 0));
        gestioncat.setText("Gestion des catégories");
        gestioncat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gestioncat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestioncatActionPerformed(evt);
            }
        });

        label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/pidev/tests/dao/user.png"))); // NOI18N

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(gestioncat, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gestionoffre, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(gestionuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(383, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(gestioncat, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gestionoffre, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gestionuser, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stat, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 32, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gestioncatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestioncatActionPerformed
        // TODO add yourthis.setVisible(false);
       
        Choix choix=new Choix();
        choix.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_gestioncatActionPerformed

    
    /**
     * @param args the command line arguments
     */
   
    
    public static void main(String args[]) {
         
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionCategories().setVisible(true);
            }
        });
        
    }
      
   
       
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton gestioncat;
    private javax.swing.JToggleButton gestionoffre;
    private javax.swing.JToggleButton gestionuser;
    private javax.swing.JLabel label1;
    private javax.swing.JPanel panel1;
    private javax.swing.JToggleButton stat;
    // End of variables declaration//GEN-END:variables

    private void findAll() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
